### PR TITLE
made a create_category function that accepts a post request from /cat…

### PR DESCRIPTION
**Pull request by jakefroeb**
…egories and returns the new category object created

### CODE REVIEW

**Comment by jakefroeb** [comment]
example post request
```
{
"label" : "python"
}
```

**Review by phillipphan — APPROVED** [review]
👍

**Review by nch66862 — APPROVED** [review]
I was able to post a new category. Something we might have to watch for when merging is when the json.dumps is called in the request handler or when it is called in the module function.

**Review by KaitlinJKelley — COMMENTED** [review]
Works; I also did json.dumps in my modules

**Pull request merged**
