### PR TITLE
Jhf edit category

### PR DESCRIPTION
**Pull request by jakefroeb**
made and update_category function that deals with the PUT method on /categories/?

### CODE REVIEW

**Comment by jakefroeb** [comment]
example put request
```
{
"id" : 2,
"label" : "update python"
}
```

**Review by phillipphan — APPROVED** [review]
changing a category works

**Review by KaitlinJKelley — APPROVED** [review]
👍

**Review by nch66862 — APPROVED** [review]
UPdated a Cat-ergory

**Pull request merged**
